export const phoneRegExp =
  /^((\\+[1-9]{1,4}[ \\-]*)|(\\([0-9]{2,3}\\)[ \\-]*)|([0-9]{2,4})[ \\-]*)*?[0-9]{3,4}?[ \\-]*[0-9]{3,4}?$/;

export const Permissions = {
  EDIT_CATEGORY: "EDIT_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",
  CREATE_CATEGORY: "CREATE_CATEGORY",
  EDIT_PRODUCT: "EDIT_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  CREATE_PRODUCT: "CREATE_PRODUCT",
  CREATE_PERMISSION: "CREATE_PERMISSION",
  CREATE_ROLE: "CREATE_ROLE",
  CREATE_USER_ROLE: "CREATE_USER_ROLE",
  RESELLER: "RESELLER"
};
